### ISSUE TITLE
Issue on all my modules's methods

### ISSUE THREAD

**Issue by kootenpv** [timothycrosley/portray#10]
Tried this with a clone of https://github.com/kootenpv/access_points (one of my simplest repos) and the result is visible in the screenshot: something goes wrong with the methods?

https://i.imgur.com/FVYV9u5.png

Quick link to the source code visible in the screenshot: https://github.com/kootenpv/access_points/blob/master/access_points/__init__.py#L164

**Comment by timothycrosley** [comment]
Thank you for alerting me to this issue!
This should now be resolved in release 1.1.0: https://timothycrosley.github.io/portray/CHANGELOG/#changelog

Thanks!

~Timothy
