### ISSUE TITLE
Method for running portray in a CI job when I commit to main?

### ISSUE THREAD

**Issue by robbintt** [timothycrosley/portray#102]
I am running portray locally but would like to run it in a github action.  Is this already done somewhere? It would be nice to set it up as an option the first time you run portray so you no longer have to maintain a local environment.

**Comment by timothycrosley** [comment]
Good question! You can see an example of this working on the cruft project here: https://github.com/cruft/cruft/blob/master/.github/workflows/docs.yml

**Comment by robbintt** [comment]
Thanks, it worked perfectly.

**Comment by robbintt** [comment]
Might be worth adding to this project, maybe someone will want to take it on.
