### ISSUE TITLE
Clarify what a "project" is in documentation

### ISSUE THREAD

**Issue by nealmcb** [timothycrosley/portray#12]
I get this traceback:

```
$ portray in_browser
 ....
  File ".../lib/python3.6/site-packages/portray/config.py", line 63, in project
    raise NoProjectFound(directory)
portray.exceptions.NoProjectFound: (NoProjectFound(...), "No Python project found in the given directory: 
```

Clarification in the error message and in the documentation for what defines a "Python project" would help.

E.g. do you require that Poetry be used and/or that there be a [pyproject\.toml file](https://poetry.eustace.io/docs/pyproject/)?

**Comment by drcongo** [comment]
I'm using poetry on my projects and I'm getting `NoProjectFound` on every project I try it on. I have no idea why.

**Comment by timothycrosley** [comment]
@drcongo are you running it in the same location as your pyproject.yaml file?

**Comment by timothycrosley** [comment]
I've done a few things in the just release 1.1.0 release (https://timothycrosley.github.io/portray/CHANGELOG/#110-august-29) to try to address this:

- Added the ability to specify modules from the command line (per @zachvalenta)
- Added a troubleshooting guide for the NoProjectFound exception
- Added links to the trouble shooting guide from the exception
- Added initial smarts to attempt to pull modules out of simple setup.py files using ast

Let me know if there is more that can be done, thanks for alerting me to this issue!

Thanks!

~Timothy

**Comment by nealmcb** [comment]
Thanks!

In particular, note the link in the error message now, to https://timothycrosley.github.io/portray/TROUBLESHOOTING/#noprojectfound:

```
  File "/home/neal/Envs/portray/lib/python3.6/site-packages/portray/config.py", line 66, in project
    raise NoProjectFound(directory)
portray.exceptions.NoProjectFound: (NoProjectFound(...), "No Python project found in the given directory: '/srv/neal/py/projects/audit_cvrs' See: https://timothycrosley.github.io/portray/TROUBLESHOOTING/#noprojectfound")
```

But I still think the top-level documentation for Portray, including the README.md, should define "project" in the Python context, since the term has a technical meeting of sorts here which is unclear, and can't be found via a straightforward google search.  I guess it means something like "something to be packaged which has a pyproject.toml or setup.py file", or "the sort of thing that pypi lets you install".
