### ISSUE TITLE
Portray silently requires README.md

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/portray#17]
From @liiight via gitter:

hi there. just stumbled into portray and it looks great!
unfortunately i cant seem to get it working. seems i get a 404 when running it

Ors-MacBook-Pro-2:notifiers orcarmi$ portray in_browser
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Module 'notifiers.utils'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Module 'notifiers.utils.schema'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it wi
ll stop working
  if not isinstance(key, collections.Hashable):
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/structure/pages.py:253: DeprecationWarning: Using the add method to register a processor or pattern is deprecated. Use the `register` method instead.
  md.treeprocessors.add("relpath", relpath, "_end")
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/markdown/core.py:128: DeprecationWarning: The 'md_globals' parameter of 'mkdocs.structure.pages._RelativePathExtension.extendMarkdown' is deprecated.
  ext._extendMarkdown(self)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/lexer.py:587: DeprecationWarning: invalid escape sequence '\s'
  .decode('unicode-escape')

██████╗  ██████╗ ██████╗ ████████╗██████╗  █████╗ ██╗   ██╗
██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚██╗ ██╔╝
██████╔╝██║   ██║██████╔╝   ██║   ██████╔╝███████║ ╚████╔╝
██╔═══╝ ██║   ██║██╔══██╗   ██║   ██╔══██╗██╔══██║  ╚██╔╝
██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║██║  ██║   ██║
╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

        Your Project with Great Documentation.

Version: 1.0.5
Copyright Timothy Edmund Crosley 2019 MIT License

Serving on 127.0.0.1:8000...
127.0.0.1 - - [27/Aug/2019 23:02:40] "GET / HTTP/1.1" 404 0

**Comment by timothycrosley** [comment]
This is fixed in portray 1.1.0: https://timothycrosley.github.io/portray/CHANGELOG/#110-august-29

**Comment by liiight** [comment]
Thanks for clarifying this. Is support for README.rst planned?

**Comment by timothycrosley** [comment]
I'm certainly open to supporting README.rst and rst in general, but haven't set any concrete plans to do so yet. Any rst support would have to take a slight backseat (if I were the one implementing it) to replacing pdoc3: https://github.com/timothycrosley/portray/issues/19
