### ISSUE TITLE
Replace pdoc3

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/portray#19]
Find or create a suitable replacement for pdoc3 given the history / state of the project

**Comment by zachvalenta** [comment]
> given the history / state of the project

Is this what you're referring to? -> https://github.com/pdoc3/pdoc/issues/64

**Comment by timothycrosley** [comment]
@zachvalenta that, and the fact the project forked under a different more restrictive license than the original (AGPL) which means it's incompatible with the MIT license used by this project. Just finished a compatible replacement: https://timothycrosley.github.io/pdocs/

**Comment by timothycrosley** [comment]
Resolved in 1.2.0: https://timothycrosley.github.io/portray/CHANGELOG/#120-september-3-2019
