### ISSUE TITLE
Generation of docs in Gitlabs CI/CD docker image does not work

### ISSUE THREAD

**Issue by PanRe** [timothycrosley/portray#41]
Hi Timothy,

Sorry bothering you again. I try to setup a CI/CD pipeline on Gitlab to automatically generate the docs as_html output. However, it does not work with the error:
"Auto generating reference documentation using pdocs
Error import src/rero/__init__.py: no module named 'rero' ".

The generation of the docs works locally on my PC with the same settings but not in the docker image setup by Gitlabs CI/CD image. The module i try to document is located in ./src/rero and i set this up in the .toml file as 

[tool.portray]
modules = ["src/rero"]

It seems to me that the copy process to the temporary folder does not work... but i am not sure. Is there a possibility to switch the generation of a temporary folder off?

**Comment by PanRe** [comment]
Solved it! My own fault, I forgot to install the module in the docker image (which is required since pdocs reads the doc strings from the installed module).

**Comment by timothycrosley** [comment]
@PanRe Glad you were able to solve it! Sorry I didn't get back to you sooner, was busy finishing up my next project: https://timothycrosley.com/

**Comment by PanRe** [comment]
Hi Timothy,
Never mind! You are highly productive as it seems. Nice projects!
