### ISSUE TITLE
Excluding modules / classes

### ISSUE THREAD

**Issue by christianhidber** [timothycrosley/portray#49]
Just stumbled across portray, it look's great. We would love to use it for our project. However I couldn't figure out how to exclude some modules / classes / parts of the docs folder. I tried to set a list of modules in pyproject.toml like this:

[tool.portray]
output_dir = "docs\portray"
docs_dir="docs"
modules=["easyagents", "easyagents.callbacks"]

But all modules and the full content of the docs directory are still included:
![image](https://user-images.githubusercontent.com/51879047/66714809-d9c8e600-edbb-11e9-8e77-fa6b28a1103e.png)

Is there a way to exclude classes / modules by pattern matching ? Like everthing ending in *test.py ? Any help is appreciated. Thanks a lot.

**Comment by jchan0087** [comment]
Hey Christian,

This is actually part of the documentation for troubleshooting, but it's definitely not intuitive to find: https://timothycrosley.github.io/pdocs/reference/pdocs/#special-docstring-conventions-used-by-pdoc, Note that this special for of pdoc to pdocs doesn't recognize `__pdoc__['KEY'] = False`, but instead requires `__pdoc__['KEY'] = None`. However, I still couldn't figure out how to exclude submodules as every extension of key didn't seem to work e.g. parent.child.func or if I want to exclude the entire submodule which is possible in pdoc parent.child. Though I got around this by deploying the documentation with ci/cd and doing an `rm -rf parent/child` before creating the site dir.

**Comment by christianhidber** [comment]
Thanks. It turned out that the problem was a syntax error in my toml file. Thus it was ignored. Now it works fine. My fault. Sorry. Thank's a lot.
