### ISSUE TITLE
Compatibility with pymdown-extensions >= 7.0

### ISSUE THREAD

**Issue by fsoubelet** [timothycrosley/portray#58]
Hi, 

The `pymdown-extensions` package has had a [major release](https://github.com/facelessuser/pymdown-extensions/releases) about two months ago. This `7.0` version adds quite a lot of nice things. Would it be possible to make portray compatible with this new version?

As I see it, they were on `6.0` when Portray was started, so running `poetry add pymdown-extensions` automatically gave the `^6.0` condition.

Hopefully changing this to `^7.0` would be enough. If not, I'd be glad to try and help.
Similarly, it would be nice to try and have compatibility with `mkdocs-material` version 5.

**Comment by fsoubelet** [comment]
Similarly, it would be nice to try and have compatibility with `mkdocs-material` version 5.

**Comment by timothycrosley** [comment]
HI @fsoubelet, I'd be thrilled to accept a PR that resolved this!

Thanks!
