### ISSUE TITLE
mkdocs 1.2 replaced DEFAULT_SCHEMA with defaults.get_schema()

### ISSUE THREAD

**Issue by Peter200lx** [timothycrosley/portray#83]
The following line needs to be updated to support mkdocs 1.2:
https://github.com/timothycrosley/portray/blob/cd60f2a22d18ec025fb341c0010de31b2523a1a2/portray/render.py#L172

https://github.com/mkdocs/mkdocs/blob/master/docs/about/release-notes.md#backward-incompatible-changes-in-12
> The `mkdocs.config.DEFAULT_SCHEMA` global variable has been replaced with the function `mkdocs.config.defaults.get_schema()`, which ensures that each instance of the configuration is unique (mkdocs/mkdocs#2289).

**Comment by voice-of-texnoforge** [comment]
I was going to report this, but you were faster and there's a fix already... yay for portray 🎉

**Comment by timothycrosley** [comment]
Hi @Peter200lx thanks for reporting and @myedibleenso thanks for your fix! portray 1.7.0 has been released with the compatibility fix in place.

**Comment by voice-of-texnoforge** [comment]
Oh yeah, my docs CI is green again ᕕ( ᐛ )ᕗ
